# Make sure you have an export preset for web and you must
# have put `<script src="coi-serviceworker.js"></script>`
# in the "Head Include" property of the preset the
# "coi-serviceworker.js" script allow setting COOP and COEP
# headers in Github Pages, without, the game will not load

name: "godot4-web-deployer"
on: push

permissions:
  contents: write

env:
  GODOT_MAJOR_MINOR_VERSION: "4.2.1" # must be a string, not a number
  GODOT_PATCH_VERSION: stable2.1

  PROJECT_FOLDER: "./project" # the path to the godot project (must contain `project.godot` file) relative to the github root path

  EXPORT_TEMPLATE: release # export with release || debug
  EXPORT_PRESET_NAME: Web # name of the preset
  EXPORT_FOLDER: build/ # just the folder where the project will be build, not really important
  EXPORT_FILENAME: index.html # export file name

  DEPLOYMENT_BRANCH: gh-pages # the name of the branch, will be automatically created if it does not exist

  GODOT_VERSION: 4.2.1

  EXPORT_NAME: build/web
  PROJECT_PATH: project

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "HTML5" ../build/web/index.html
      - name: Add coi-service-worker
       run: |
         git clone https://github.com/gzuidhof/coi-serviceworker.git
         mv coi-serviceworker/coi-serviceworker.js ${EXPORT_FOLDER}/coi-serviceworker.js
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.